# dev environment

server:
  port: 9300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

spring:
  profiles: dev

  application:
    name: shop-system

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 0
      maximum-pool-size: 3
      auto-commit: false
      idle-timeout: 50000
      pool-name: DatebookHikariCP
      max-lifetime: 90000
      connection-timeout: 30000
      connection-test-query: SELECT 1 from dual

# 指定sql映射文件位置
mybatis:
  mapper-locations: classpath:mappers/*.xml
