# dev environment

server:
  port: 9300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

spring:
  profiles: dev

  application:
    name: shop-system

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456


# 指定sql映射文件位置
mybatis:
  mapper-locations: classpath:mappers/*.xml
