# dev environment
server:
  port: 9200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
spring:
  profiles: dev

  application:
    name: shop-seckill

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 0
      maximum-pool-size: 3
      auto-commit: false
      idle-timeout: 50000
      pool-name: DatebookHikariCP
      max-lifetime: 90000
      connection-timeout: 30000
      connection-test-query: SELECT 1 from dual

#  redis:
#    database: 0
#    host: 62.234.86.114
#    port: 6379
#    password: "^ZHAOQIN^&18040027158ZHAOQIN"
#    timeout: 6000ms
#    lettuce:
#      pool:
#        max-active: 1
#        max-wait: -1ms
#        max-idle: 1
#        min-idle: 0
#        time-between-eviction-runs: 60000ms
  redis:
    database: 0
    host: 39.105.193.132
    port: 6379
    password: "^&ASFHGGmnAASF2254=_"
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1
        max-wait: -1ms
        max-idle: 1
        min-idle: 0
        time-between-eviction-runs: 60000ms

  session:
    store-type: redis


  rabbitmq:
    host: 62.234.86.114
    port: 5672
    username: guest
    password: guest

# 指定sql映射文件位置
mybatis:
  mapper-locations: classpath:mappers/*.xml